# sdfreadergui_ui.tcl --
#
# UI generated by GUI Builder Build 146 on 2009-07-27 14:49:32 from:
#    /media/KINGSTON/Tcl-Tk/SDFreader/SDFReader/sdfreadergui.ui
# THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
# The associated callback file should be modified instead.
#

# Declare the namespace for this dialog
namespace eval sdfreadergui {}

package require Tk
# sdfreadergui::ui --
#
#   Create the UI for this dialog.
#
# ARGS:
#   root     the parent window for this form
#   args     a catch-all for other args, but none are expected
#
proc sdfreadergui::ui {root args} {
    # this handles '.' as a special case
    set base [expr {($root == ".") ? "" : $root}]
    variable ROOT $root
    variable BASE $base
    variable SCRIPTDIR ; # defined in main script


    # Widget Initialization
    variable _button_prev [button $BASE._button_prev \
	    -command [namespace code [list _button_prev_command]] \
	    -text "<< Previous"]
    variable _button_next [button $BASE._button_next \
	    -command [namespace code [list _button_next_command]] \
	    -text "Next >>"]
    variable _label_1 [label $BASE._label_1 \
	    -anchor "w" \
	    -borderwidth 1 \
	    -font {helvetica 8} \
	    -justify "left" \
	    -relief "sunken" \
	    -text "statusbar1" \
	    -textvariable "SDF::status1"]
    variable _label_2 [label $BASE._label_2 \
	    -anchor "e" \
	    -borderwidth 1 \
	    -font {helvetica 8} \
	    -justify "right" \
	    -relief "sunken" \
	    -text "statusbar 2" \
	    -textvariable "SDF::status2"]
    variable text_data [text $BASE.text_data \
	    -background "#ffffff" \
	    -font {helvetica 9} \
	    -height 0 \
	    -width 0 \
	    -wrap "none" \
	    -xscrollcommand [list $BASE._scrollbar_3 set] \
	    -yscrollcommand [list $BASE._scrollbar_2 set]]
    variable _scrollbar_2 [scrollbar $BASE._scrollbar_2 \
	    -command [list $BASE.text_data yview] \
	    -width 10]
    variable _scrollbar_3 [scrollbar $BASE._scrollbar_3 \
	    -command [list $BASE.text_data xview] \
	    -orient "horizontal" \
	    -width 10]
    variable mol_canvas [canvas $BASE.mol_canvas \
	    -background "#ffffff" \
	    -height 0 \
	    -width 0 \
	    -xscrollcommand [namespace code [list mol_canvas_xscrollcommand]] \
	    -yscrollcommand [namespace code [list mol_canvas_yscrollcommand]]]
    variable entry_record [entry $BASE.entry_record \
	    -background "#ffffff" \
	    -font {helvetica 9} \
	    -invalidcommand [namespace code [list entry_record_invalidcommand]] \
	    -textvariable "SDF::current_record" \
	    -validatecommand [namespace code [list entry_record_validatecommand]] \
	    -width 10 \
	    -xscrollcommand [namespace code [list entry_record_xscrollcommand]]]
    variable _button_go [button $BASE._button_go \
	    -command [namespace code [list _button_go_command]] \
	    -text "Go"]
    variable _label_4 [label $BASE._label_4 \
	    -anchor "e" \
	    -font {helvetica 8} \
	    -text "Record:"]
    variable _button_stop [button $BASE._button_stop \
	    -command [namespace code [list _button_stop_command]] \
	    -state "disabled" \
	    -text "STOP"]
    variable _button_search [button $BASE._button_search \
	    -command [namespace code [list _button_search_command]] \
	    -text "Search"]
    variable menu [menu $BASE.menu]
    variable menuitem1 [menu $BASE.menuitem1 \
	    -tearoff 0]
    $BASE.menu add cascade \
	    -label "File" \
	    -underline 0 \
	    -menu $BASE.menuitem1
    $BASE.menuitem1 add command \
	    -accelerator "Ctrl+o" \
	    -command "SDF::open_SDF" \
	    -label "Open SDF" \
	    -underline 0
    $BASE.menuitem1 add command \
	    -accelerator "Ctr+d" \
	    -command "SDF::open_db" \
	    -label "Open database" \
	    -underline 5
    $BASE.menuitem1 add command \
	    -accelerator "Ctrl+s" \
	    -command "SDF::save_db" \
	    -label "Save database"


    # Geometry Management

    grid $BASE._button_prev -in $root -row 3 -column 1 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "nsew"
    grid $BASE._button_next -in $root -row 3 -column 2 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "nsew"
    grid $BASE._label_1 -in $root -row 4 -column 1 \
	    -columnspan 5 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "nsew"
    grid $BASE._label_2 -in $root -row 4 -column 6 \
	    -columnspan 4 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "nsew"
    grid $BASE.text_data -in $root -row 1 -column 6 \
	    -columnspan 3 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "news"
    grid $BASE._scrollbar_2 -in $root -row 1 -column 9 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "ns"
    grid $BASE._scrollbar_3 -in $root -row 2 -column 6 \
	    -columnspan 3 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "ew"
    grid $BASE.mol_canvas -in $root -row 1 -column 1 \
	    -columnspan 5 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 2 \
	    -sticky "news"
    grid $BASE.entry_record -in $root -row 3 -column 4 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "nsew"
    grid $BASE._button_go -in $root -row 3 -column 5 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "nsew"
    grid $BASE._label_4 -in $root -row 3 -column 3 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "nsew"
    grid $BASE._button_stop -in $root -row 3 -column 8 \
	    -columnspan 2 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "nsew"
    grid $BASE._button_search -in $root -row 3 -column 6 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky ""

    # Resize Behavior
    grid rowconfigure $root 1 -weight 1 -minsize 188 -pad 0
    grid rowconfigure $root 2 -weight 0 -minsize 2 -pad 0
    grid rowconfigure $root 3 -weight 0 -minsize 2 -pad 0
    grid rowconfigure $root 4 -weight 0 -minsize 2 -pad 0
    grid columnconfigure $root 1 -weight 0 -minsize 47 -pad 0
    grid columnconfigure $root 2 -weight 0 -minsize 65 -pad 0
    grid columnconfigure $root 3 -weight 0 -minsize 33 -pad 0
    grid columnconfigure $root 4 -weight 0 -minsize 71 -pad 0
    grid columnconfigure $root 5 -weight 0 -minsize 2 -pad 0
    grid columnconfigure $root 6 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $root 7 -weight 1 -minsize 217 -pad 0
    grid columnconfigure $root 8 -weight 0 -minsize 55 -pad 0
    grid columnconfigure $root 9 -weight 0 -minsize 2 -pad 0
    $ROOT configure -menu $BASE.menu
}
